services:
  app:
    build: .
    container_name: app
    # maybe expose internal port
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

#   postgres:
#     image: postgres:14
#     environment:
#       POSTGRES_DB: your_db
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: secret
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     networks:
#       - app-network

networks:
  app-network:

# volumes:
#   pg_data:
