services:
  - type: web
    name: laravel-app
    env: docker
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromService:
          name: beta_sbaread_db
          type: database       
          property: connectionString

databases:
  - name: beta_sbaread_db
    databaseName: beta_sbaread_db
    user: beta_sbaread_user











# services:
#   - type: web
#     name: laravel-app
#     env: docker
#     # repo:
#     branch: main
#     dockerfilePath: ./Dockerfile
#     envVars:
#       - key: APP_ENV
#         value: production
#       - key: APP_KEY
#         sync: false
#       - key: APP_DEBUG
#         value: false
#       - key: DB_CONNECTION
#         value: pgsql
#       - key: DB_HOST
#         fromService:
#           name: beta_sbaread_db
#           type: postgres
#           property: host
#       - key: DB_PORT
#         value: 5432
#       - key: DB_DATABASE
#         fromService:
#           name: beta_sbaread_db
#           type: postgres
#           property: database
#       - key: DB_USERNAME
#         fromService:
#           name: beta_sbaread_db
#           type: postgres
#           property: user
#       - key: DB_PASSWORD
#         fromService:
#           name: beta_sbaread_db
#           type: postgres
#           property: password

# databases:
#   - name: beta_sbaread_db
#     databaseName: beta_sbaread_db
#     user: beta_sbaread_user
